### ISSUE TITLE
[Bug] Nested validation using dataclasses

### ISSUE THREAD

**Issue by morph027** [sanic-org/sanic-ext#140]
**Describe the bug**

When using nested dataclasses, validation does not work properly.

`curl -X POST localhost:8000/test`

```
⚠️ 400 — Bad Request
====================
Invalid request body: Nested. Error: Value '<factory>' is not a dict
```

**To Reproduce**

```python
from sanic import Sanic
from sanic.response import text
from sanic_ext import openapi, validate
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, Optional

app = Sanic("test")


@dataclass
class Choices(Enum):
    foo = "foo"
    bar = "bar"


@dataclass
class Child:
    foobar: Optional[Choices] = field(default_factory=Choices)


@dataclass
class Nested:
    child: Optional[Child] = field(default_factory=dict)


@app.middleware("request")
async def dummy_body_if_empty(request):
    if not request.body:
        request.body = b'{}'


@app.post('/test')
@openapi.body({"application/json": Nested}, required=True)
@validate(Nested)
async def handler(request, body: Nested):
    return text('OK')
```

**Expected behavior**

`curl -X POST localhost:8000/test` works.

**Environment (please complete the following information):**
 - OS: Debian/Ubuntu
 - Version 22.9.0

**Comment by scardozos** [comment]
Hello,

I've been looking into this and it seems that the underlying issue does not have to do with dataclasses or the fact that they're nested with each other.

The culprit for the issue you're encountering seems to be that Enums classes are not a valid type to take into consideration for validation for the moment, as a `dict` type seems to be expected. 

I believe that this is expected behavior having in mind how checks are made (against types, not against specific values) - but I may be wrong though.

Nonetheless, for the time being, you can use custom validation by specifying a __post_init__ function within the class in which you expect an enum response.

Please find a working example in which it can be seen that nested dataclasses are not an issue here:

The code:

```python
from sanic import Sanic
from sanic.response import text
from sanic_ext import openapi, validate
from sanic.exceptions import BadRequest
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, Optional

app = Sanic("test")


@dataclass
class AnimalTypes(Enum):
    mammal = "mammal"
    bird = "bird"

@dataclass
class Family:
    animal_group: str 
    
    def __post_init__(self):
        self.validate_animal_group()

    def validate_animal_group(self):
        vals = [animal_type.value for animal_type in AnimalTypes]
        if self.animal_group not in vals:
            raise BadRequest("Animal must be of a valid type")

@dataclass
class Animal:
    name: str
    family: Family


@app.post('/test')
@openapi.body({"application/json": Animal}, required=True)
@validate(json=Animal)
async def nested_w_enum(request, body: Animal):
    return text(f'The animal is called: {body.name}, and it is of type: {body.family.animal_group}')

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=1234, debug=True, auto_reload=True)
```

Valid request:
`curl -X POST -d '{"name":"Lion","family":{"animal_group":"mammal"}}' localhost:1234/test`
response:
`The animal is called: Lion, and it is of type: mammal`

Invalid Request:
`curl -X POST -d '{"name":"Lion","family":{"animal_group":"dragon"}}' localhost:1234/test`

response:
```
⚠️ 400 — Bad Request
====================
Animal must be of a valid type
``` 

PD: You can specify `animal_group: Union[AnimalTypes, str]` adding Union to the `typing` imports so that it's visible from the OpenAPI spec.

**Comment by morph027** [comment]
Thanks for having a look. I'm using the `__post_ini__` hack at a different level too, just did not come to my mind for this ;)

https://gitlab.com/morph027/python-signal-cli-rest-api/-/blob/main/python_signal_cli_rest_api/api/groups.py#L168-L181 (Here i also provide different views for openapi/validator as at the time writing this i could not find out how to trick it).

**Comment by morph027** [comment]
Works so far. I'm still splitting out the classes for openapi docs and validation ((example)[https://gitlab.com/morph027/python-signal-cli-rest-api/-/blob/main/python_signal_cli_rest_api/api/configuration/__init__.py#L34-L81]) but that's fine.

I'm wondering if using pydantic models will be less hassel...

**Comment by ahopkins** [comment]
> I'm wondering if using pydantic models will be less hassel...

Almost without a doubt 😆

**Comment by morph027** [comment]
> > I'm wondering if using pydantic models will be less hassel...
> 
> Almost without a doubt laughing

Good to know, will have a look...some late night after work work :)

**Comment by morph027** [comment]
Just for the record, pydantic models are doing everything as expected :heart_eyes:
