### ISSUE TITLE
Remove external dependency

### ISSUE THREAD

**Issue by eric-nieuwland** [sanic-org/sanic-ext#3]
The swagger page generated by openapi extension depends on `pagecdn.io/lib/swagger-ui/latest/`. My application will be deployed in an environment where it will not be possible to resolve this dependency at runtime.

Please make the source for these resources configurable with `pagecdn.io/lib/swagger-ui/latest/` as default. This will allow me to serve them from the application itself or a server nearby.

**Comment by ahopkins** [comment]
This was a consideration. Not so much in generating and injecting values into the HTML as much as just allowing you to drop in your own. 

```python
Extend(app, config=Config(oas_path_to_swagger_html="..."))
```

One of the things that still needs work in configuration. There are no docs yet (working on it). You do not _NEED_ to use the `Config` object. You can also do it as a dict:

```python
Extend(app, config={"oas_path_to_swagger_html": "..."})
```

It is there just so that there is a convenient type annotated object to help you remember what the options are.

You can set the value as you normally would with any other Sanic config using: `OAS_PATH_TO_SWAGGER_HTML`. For example:

```python
app.config.OAS_PATH_TO_SWAGGER_HTML = "..."
```

**Comment by eric-nieuwland** [comment]
Works for me. Thanks.
