### ISSUE TITLE
[Bug] Dependency injection fails when multiple routes share the same name

### ISSUE THREAD

**Issue by xmcp** [sanic-org/sanic-ext#60]
**Describe the bug**

If multiple route handlers have the same name, sanic-ext will treat them as one route during dependency injection, causing a HTTP 500 because passed `kwargs` does not correspond to the function signature.

**Screenshots**

![image](https://user-images.githubusercontent.com/6646473/153749531-0f521e5e-401e-4239-8426-fae2be5231c8.png)

**To Reproduce**

Consider this code:

```python
from sanic import Sanic, response

app = Sanic('test')

class Object:
    pass
    
app.ext.add_dependency(Object, lambda req: None)

@app.route('/foo')
def handler(req, foo: Object):
    return response.text('foo')
    
@app.route('/bar')
def handler(req, bar: Object):
    return response.text('bar')
    
app.run(debug=True)
```

Then visit `/foo`. It shows a HTTP 500 error:

```
Traceback (most recent call last):
  File "handle_request", line 81, in handle_request
    error_logger,
TypeError: handler() got an unexpected keyword argument 'bar'
```

**Expected behavior**

I'm not sure whether it is discouraged to use a same name (`handler` in the example above) across different route handlers.

I believe sanic-ext should either support this or warn users about this caveat.

**Environment (please complete the following information):**
 - OS: Windows 10 (19044.1466)
 - Browser: not related
 - Version: sanic 21.12.1, sanic-ext 22.1.2

**Additional context**

Maybe the [`signature_registry`](https://github.com/sanic-org/sanic-ext/blob/1ad406a462/sanic_ext/extensions/injection/injector.py#L15) should use something else as the key.

**Comment by ahopkins** [comment]
This is discouraged for sure. It probably should be a warning by the core project.

**Comment by xmcp** [comment]
I surveyed the Sanic docs for a while before posting this issue, and I wonder whether duplicate route names are really discouraged.

Here are some findings:

- [The API doc for `Sanic.route`](https://sanic.readthedocs.io/en/stable/sanic/api/app.html#sanic.app.Sanic.route) says that the `name` is an `Optional[str]` as a "user defined route name for url_for". It suggests that a unique name is optional and only needed by `url_for`.
- [The Sanic user guide](https://sanic.dev/en/guide/basics/routing.html#adding-a-route) itself heavily uses `handler` as the function name, which is not unique.
- It actually works perfectly fine if handler names are not unique.

By comparison, Flask [said in its API doc](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.add_url_rule) that endpoint names should not duplicate, and it raises `AssertionError: View function mapping is overwriting an existing endpoint function: handler` before server startup if the developer really violates this.

So if you are sure that handler names must be unique in Sanic, I would suggest a warning both in the user guide and in the Sanic code.

**Comment by ahopkins** [comment]
1. url_for is the only place the core project uses it. However, we've been moving towards pushing naming in Apps and Blueprints for several years now. In last LTS (for example) strict enforcement is enabled for app and blueprint naming. This is part of that shift.
2. It uses handler because that's fairly descriptive for what it is. AFAIK it does not use two similarly named functions in the same example. If it does we should fix that.
3. Yes, it works, which is why we have not broken that and do not have a current plan to. I'd like to strictly enforce, but there has not yet been a need to push that. Other python tools like flake8 will yell at you for this.
4. What Flask does is fairly irrelevant and would not sway my opinion in either direction.
5. There is not currently a unique naming requirement. I would like to enforce that, but we are several release cycles away from being able to do that.

With that all said, we probably should add the warning to 21.3 and aim for enforcement by the end of the year.
